$LOAD_PATH << '.'
require 'book'
require 'classroom'
require 'person'
require 'rental'
require 'services'
require 'student'
require 'teacher'
require 'books_controller'
require 'people_controller'
require 'rentals_controller'
require 'nameable'
require 'decorator'
require 'capitalize_decorator'
require 'trimmer_decorator'
require 'data'
